return function(h, loaded)
    local Geo = loaded.ns.Geo
    local world = dofile("test/fake_world.lua")()

    h.describe("Geo.ToWorld", function()
        h.it("converts map coords to continent and world yards", function()
            local c, x, y = Geo.ToWorld(world.Places, 1, 0.25, 0.5)
            h.eq(c, 1)
            h.eq(x, 5000)
            h.eq(y, 7500)
        end)
        h.it("returns nil for a map it does not know", function()
            h.eq(Geo.ToWorld(world.Places, 99, 0.5, 0.5), nil)
        end)
        h.it("returns nil without coordinates", function()
            h.eq(Geo.ToWorld(world.Places, 1, nil, nil), nil)
        end)
    end)

    h.describe("Geo.Distance", function()
        h.it("measures yards on one continent", function()
            h.eq(Geo.Distance({ c = 1, x = 0, y = 0 }, { c = 1, x = 300, y = 400 }), 500)
        end)
        h.it("is infinite across continents", function()
            h.eq(Geo.Distance({ c = 1, x = 0, y = 0 }, { c = 0, x = 0, y = 0 }), math.huge)
        end)
        h.it("is infinite when a position is missing", function()
            h.eq(Geo.Distance(nil, { c = 0, x = 0, y = 0 }), math.huge)
        end)
    end)
end
