return function(h, loaded)
    local Prefs = loaded.ns.Prefs

    h.describe("Prefs.Init", function()
        h.it("fills an empty table with the defaults", function()
            local db = Prefs.Init(nil)
            h.eq(db.layout, "wide")
            h.eq(#db.recents, 0)
            h.eq(db.minimap.angle, 215)
            h.eq(db.minimap.hide, false)
        end)
        h.it("keeps what the player already chose", function()
            local db = Prefs.Init({ layout = "tall", minimap = { angle = 10 } })
            h.eq(db.layout, "tall")
            h.eq(db.minimap.angle, 10)
            h.eq(db.minimap.hide, false)
        end)
        h.it("repairs a layout it does not know", function()
            h.eq(Prefs.Init({ layout = "sideways" }).layout, "wide")
        end)
        h.it("gives every table its own copy of the defaults", function()
            local a, b = Prefs.Init(nil), Prefs.Init(nil)
            a.recents[1] = "Orgrimmar"
            h.eq(#b.recents, 0)
        end)
    end)

    h.describe("Prefs.ToggleLayout", function()
        h.it("flips between wide and tall", function()
            local db = Prefs.Init(nil)
            h.eq(Prefs.ToggleLayout(db), "tall")
            h.eq(Prefs.ToggleLayout(db), "wide")
            h.eq(db.layout, "wide")
        end)
    end)

    h.describe("Prefs.Remember", function()
        h.it("puts the newest destination first", function()
            local db = Prefs.Init(nil)
            Prefs.Remember(db, "Orgrimmar")
            Prefs.Remember(db, "Undercity")
            h.eq(table.concat(db.recents, ","), "Undercity,Orgrimmar")
        end)
        h.it("moves a repeat to the front instead of listing it twice", function()
            local db = Prefs.Init(nil)
            Prefs.Remember(db, "Orgrimmar")
            Prefs.Remember(db, "Undercity")
            Prefs.Remember(db, "Orgrimmar")
            h.eq(table.concat(db.recents, ","), "Orgrimmar,Undercity")
        end)
        h.it("keeps only the newest eight", function()
            local db = Prefs.Init(nil)
            for i = 1, 10 do
                Prefs.Remember(db, "Place " .. i)
            end
            h.eq(#db.recents, Prefs.MAX_RECENTS)
            h.eq(db.recents[1], "Place 10")
            h.eq(db.recents[8], "Place 3")
        end)
        h.it("ignores an empty name", function()
            local db = Prefs.Init(nil)
            Prefs.Remember(db, "")
            Prefs.Remember(db, nil)
            h.eq(#db.recents, 0)
        end)
    end)

    h.describe("Prefs window positions", function()
        h.it("saves and returns a position per window", function()
            local db = Prefs.Init(nil)
            h.eq(Prefs.Position(db, "planner"), nil)
            Prefs.SavePosition(db, "planner", "CENTER", "TOPLEFT", 12, -30)
            local p = Prefs.Position(db, "planner")
            h.eq(p.point, "CENTER")
            h.eq(p.relativePoint, "TOPLEFT")
            h.eq(p.x, 12)
            h.eq(p.y, -30)
        end)
        h.it("reads an older saved position with no relativePoint as matching point", function()
            local db = Prefs.Init(nil)
            db.positions.planner = { point = "BOTTOMRIGHT", x = 4, y = 8 }
            local p = Prefs.Position(db, "planner")
            h.eq(p.relativePoint, "BOTTOMRIGHT")
        end)
    end)
end
