return function(h, loaded)
    local Prefs = loaded.ns.Prefs

    h.describe("Prefs.Init", function()
        h.it("fills an empty table with the defaults", function()
            local db = Prefs.Init(nil)
            h.eq(db.layout, nil, "there is no layout choice any more")
            h.eq(#db.recents, 0)
            h.eq(db.minimap.angle, 215)
            h.eq(db.minimap.hide, false)
        end)
        h.it("gives the flight-path store a home and keeps the one it has", function()
            h.eq(type(Prefs.Init(nil).known), "table")
            local kept = { ["A-B"] = { [1] = true } }
            h.eq(Prefs.Init({ known = kept }).known, kept)
            h.eq(type(Prefs.Init({ known = "junk" }).known), "table", "a hostile value is repaired")
        end)
        h.it("gives the saved trips a home and keeps the one it has", function()
            h.eq(type(Prefs.Init(nil).trips), "table")
            local kept = { ["A-B"] = { to = "Orgrimmar" } }
            h.eq(Prefs.Init({ trips = kept }).trips, kept)
            h.eq(type(Prefs.Init({ trips = "junk" }).trips), "table", "a hostile value is repaired")
        end)
        h.it("keeps what the player already chose", function()
            local db = Prefs.Init({ minimap = { angle = 10 } })
            h.eq(db.minimap.angle, 10)
            h.eq(db.minimap.hide, false)
        end)
        h.it("drops a layout choice saved before the switch was removed", function()
            h.eq(Prefs.Init({ layout = "tall" }).layout, nil)
        end)
        h.it("gives every table its own copy of the defaults", function()
            local a, b = Prefs.Init(nil), Prefs.Init(nil)
            a.recents[1] = "Orgrimmar"
            h.eq(#b.recents, 0)
        end)
        h.it("repairs hostile recents, positions and minimap values", function()
            local db = Prefs.Init({ recents = "nope", positions = 5, minimap = "nope" })
            h.eq(#db.recents, 0)
            h.eq(type(db.positions), "table")
            h.eq(db.minimap.angle, 215)
            h.eq(db.minimap.hide, false)
        end)
        h.it("repairs a hostile minimap.hide inside an otherwise fine table", function()
            local db = Prefs.Init({ minimap = { angle = 10, hide = "yes" } })
            h.eq(db.minimap.angle, 10)
            h.eq(db.minimap.hide, false)
        end)
    end)

    h.describe("Prefs.Remember", function()
        h.it("puts the newest destination first", function()
            local db = Prefs.Init(nil)
            Prefs.Remember(db, "Orgrimmar")
            Prefs.Remember(db, "Undercity")
            h.eq(table.concat(db.recents, ","), "Undercity,Orgrimmar")
        end)
        h.it("moves a repeat to the front instead of listing it twice", function()
            local db = Prefs.Init(nil)
            Prefs.Remember(db, "Orgrimmar")
            Prefs.Remember(db, "Undercity")
            Prefs.Remember(db, "Orgrimmar")
            h.eq(table.concat(db.recents, ","), "Orgrimmar,Undercity")
        end)
        h.it("keeps only the newest eight", function()
            local db = Prefs.Init(nil)
            for i = 1, 10 do
                Prefs.Remember(db, "Place " .. i)
            end
            h.eq(#db.recents, Prefs.MAX_RECENTS)
            h.eq(db.recents[1], "Place 10")
            h.eq(db.recents[8], "Place 3")
        end)
        h.it("ignores an empty name", function()
            local db = Prefs.Init(nil)
            Prefs.Remember(db, "")
            Prefs.Remember(db, nil)
            h.eq(#db.recents, 0)
        end)
    end)

    h.describe("Prefs window positions", function()
        h.it("saves and returns a position per window", function()
            local db = Prefs.Init(nil)
            h.eq(Prefs.Position(db, "planner"), nil)
            Prefs.SavePosition(db, "planner", "CENTER", "TOPLEFT", 12, -30)
            local p = Prefs.Position(db, "planner")
            h.eq(p.point, "CENTER")
            h.eq(p.relativePoint, "TOPLEFT")
            h.eq(p.x, 12)
            h.eq(p.y, -30)
        end)
        h.it("reads an older saved position with no relativePoint as matching point", function()
            local db = Prefs.Init(nil)
            db.positions.planner = { point = "BOTTOMRIGHT", x = 4, y = 8 }
            local p = Prefs.Position(db, "planner")
            h.eq(p.relativePoint, "BOTTOMRIGHT")
        end)
        h.it("ignores a hostile saved position", function()
            local db = Prefs.Init(nil)
            db.positions.planner = { point = 5, x = "a", y = -30 }
            h.eq(Prefs.Position(db, "planner"), nil)
        end)
        h.it("ignores a non-table entry", function()
            local db = Prefs.Init(nil)
            db.positions.planner = "not a table"
            h.eq(Prefs.Position(db, "planner"), nil)
        end)
        h.it("falls back to point when relativePoint is hostile", function()
            local db = Prefs.Init(nil)
            db.positions.planner = { point = "CENTER", relativePoint = 5, x = 1, y = 2 }
            h.eq(Prefs.Position(db, "planner").relativePoint, "CENTER")
        end)
    end)

    h.describe("the hearthstone saving", function()
        h.it("defaults to five minutes", function()
            local db = Prefs.Init(nil)
            h.eq(db.hearthSaving, Prefs.HEARTH_SAVING_DEFAULT)
            h.eq(db.hearthSaving, 300)
        end)
        h.it("keeps a value the player chose, including zero", function()
            h.eq(Prefs.Init({ hearthSaving = 0 }).hearthSaving, 0)
            h.eq(Prefs.Init({ hearthSaving = 90 }).hearthSaving, 90)
        end)
        h.it("replaces a hostile or negative value with the default", function()
            h.eq(Prefs.Init({ hearthSaving = "soon" }).hearthSaving, 300)
            h.eq(Prefs.Init({ hearthSaving = -1 }).hearthSaving, 300)
            h.eq(Prefs.Init({ hearthSaving = {} }).hearthSaving, 300)
        end)
    end)

    h.describe("the arrival radii", function()
        local ARRIVE = loaded.ns.Trip.ARRIVE
        h.it("default to Trip's own radii", function()
            local db = Prefs.Init(nil)
            h.eq(db.arrive.ride, ARRIVE.ride)
            h.eq(db.arrive.fly, ARRIVE.fly)
            h.eq(db.arrive.transport, ARRIVE.zeppelin)
            h.eq(db.arrive.hearth, ARRIVE.hearth)
            for key, range in pairs(Prefs.ARRIVE) do
                for _, kind in ipairs(range.kinds) do
                    h.eq(range.default, ARRIVE[kind], key .. " covers " .. kind .. " at Trip's radius")
                end
            end
        end)
        h.it("keep an in-range value the player chose", function()
            local db = Prefs.Init({ arrive = { ride = 20, transport = 100 } })
            h.eq(db.arrive.ride, 20)
            h.eq(db.arrive.transport, 100, "the floor itself is allowed")
            h.eq(db.arrive.fly, 150, "a missing one is filled in")
        end)
        h.it("repair hostile and out-of-range values", function()
            local db = Prefs.Init({ arrive = { ride = "near", fly = 5, transport = 5000, hearth = 0 / 0 } })
            h.eq(db.arrive.ride, 40, "not a number")
            h.eq(db.arrive.fly, 150, "under the floor")
            h.eq(db.arrive.transport, 800, "over the ceiling")
            h.eq(db.arrive.hearth, 300, "NaN")
            h.eq(Prefs.Init({ arrive = "junk" }).arrive.ride, 40, "a hostile table is replaced")
        end)
        h.it("fan the one transport value out to zeppelin, boat and tram", function()
            local db = Prefs.Init({ arrive = { transport = 300 } })
            local radii = Prefs.ArriveRadii(db)
            h.eq(radii.zeppelin, 300)
            h.eq(radii.boat, 300)
            h.eq(radii.tram, 300)
            h.eq(radii.ride, 40)
            h.eq(radii.fly, 150)
            h.eq(radii.hearth, 300)
        end)
        h.it("Reset puts the hearthstone and every radius back", function()
            local db = Prefs.Init({ hearthSaving = 0,
                                    arrive = { ride = 20, fly = 50, transport = 100, hearth = 1000 } })
            Prefs.Reset(db)
            h.eq(db.hearthSaving, Prefs.HEARTH_SAVING_DEFAULT)
            for key, range in pairs(Prefs.ARRIVE) do
                h.eq(db.arrive[key], range.default, key)
            end
        end)
    end)

    h.describe("Prefs.Step", function()
        h.it("moves by the range's step and clamps at both ends", function()
            local ride = Prefs.ARRIVE.ride
            h.eq(Prefs.Step(40, ride, 1), 50)
            h.eq(Prefs.Step(40, ride, -1), 30)
            h.eq(Prefs.Step(200, ride, 1), 200, "the ceiling")
            h.eq(Prefs.Step(10, ride, -1), 10, "the floor")
            h.eq(Prefs.Step(45, Prefs.HEARTH_MINUTES, -1), 30, "a value /gps hearth set above the range comes in")
            h.eq(Prefs.Step(nil, ride, -1), 10, "a value it cannot read starts from the floor")
        end)
    end)

end
