return function(h, loaded)
    local Search = loaded.ns.Search
    local world = dofile("test/fake_world.lua")()

    h.describe("Search.ShortName", function()
        h.it("drops the zone after the comma", function()
            h.eq(Search.ShortName("Crossroads, The Barrens"), "Crossroads")
        end)
        h.it("leaves a plain name alone", function()
            h.eq(Search.ShortName("Moonglade"), "Moonglade")
        end)
    end)

    h.describe("Search.Find", function()
        h.it("matches without caring about case", function()
            local found = Search.Find(world, "ALP", "H")
            h.eq(#found, 1)
            h.eq(found[1].name, "Alpha")
            h.eq(found[1].nodeID, 1)
        end)
        h.it("puts names that start with the text first", function()
            local found = Search.Find(world, "e", "H")
            h.eq(found[1].name, "Eastland")
        end)
        h.it("hides the other faction's flight stops", function()
            h.eq(#Search.Find(world, "echo", "H"), 0)
            h.eq(#Search.Find(world, "echo", "A"), 1)
        end)
        h.it("gives a zone its centre as the target", function()
            local zone = Search.Find(world, "westland", "H")[1]
            h.eq(zone.kind, "zone")
            h.eq(zone.c, 1)
            h.eq(zone.x, 5000)
            h.eq(zone.y, 5000)
        end)
        h.it("returns nothing for empty text", function()
            h.eq(#Search.Find(world, "", "H"), 0)
        end)
        h.it("respects the limit", function()
            h.eq(#Search.Find(world, "a", "H", 2), 2)
        end)
    end)

    h.describe("Search.Exact", function()
        h.it("finds a bind name that matches a stop", function()
            h.eq(Search.Exact(world, "delta").nodeID, 4)
        end)
        h.it("returns nil for an inn it does not know", function()
            h.eq(Search.Exact(world, "Some Backwater Inn"), nil)
        end)
    end)
end
