std = "lua51"
max_line_length = 120
self = false
globals = {
    "SLASH_GOBLINPS1", "SlashCmdList", "GoblinPSDB", "GoblinPSCharDB",
    "GoblinPS_OnAddonCompartmentClick", "UISpecialFrames",
    "GoblinPSMinimapButton", "GoblinPSPlanner", "GoblinPSSettings", "GoblinPSWhereBox",
}
read_globals = {
    "print",
    "UnitFactionGroup", "GetBindLocation", "UnitLevel", "UnitName", "GetRealmName",
    "GetPlayerFacing", "UnitOnTaxi", "GetSubZoneText", "GetMinimapZoneText",
    "C_TaxiMap", "C_Map", "C_Item", "C_SuperTrack", "UiMapPoint", "C_AddOns",
    "CreateFrame", "Enum",
    "UIParent", "Minimap", "GameTooltip", "GetCursorPosition",
}
files["GoblinPS/Data/Places.lua"] = { max_line_length = false }
files["GoblinPS/Data/Nodes.lua"] = { max_line_length = false }
files["GoblinPS/Data/Flights.lua"] = { max_line_length = false }
-- Hand-written, one crossing per line with its zone names as a trailing comment.
files["GoblinPS/Data/Crossings.lua"] = { max_line_length = false }
-- Generated by tools/make_art.py, one part per line with a size comment; a
-- long part name (e.g. planner-frame-wide) can push a row past 120 columns.
files["GoblinPS/Data/Art.lua"] = { max_line_length = false }
-- The UI smoke test installs a fake frame API into the globals.
files["test/fake_frames.lua"] = { globals = { "print" } }
files["test/test_ui.lua"] = { globals = { "print" } }
