-- Generated by tools/make_art.py. Do not edit.
-- Each part was scaled to the size it draws at, then padded up to a
-- power-of-two canvas. l, r, t, b crop that padding away: pass them straight
-- to texture:SetTexCoord(l, r, t, b). cw, ch are that padded canvas's own
-- pixel size (what the file on disk actually is), not the pre-scale source
-- art -- a cover-crop needs the shipped aspect ratio, and l/r/t/b are
-- fractions OF cw/ch, not of the master PNG.
local _, ns = ...
ns.Data = ns.Data or {}

ns.Data.Art = {
    ["dash-body"] = { file = "dash-body", l = 0, r = 1, t = 0, b = 1, cw = 256, ch = 256 },  -- 256x256 art on 256x256
    ["dash-screen"] = { file = "dash-screen", l = 0, r = 1, t = 0, b = 1, cw = 256, ch = 256 },  -- 256x256 art on 256x256
    ["dash-compass"] = { file = "dash-compass", l = 0, r = 1, t = 0, b = 1, cw = 256, ch = 256 },  -- 256x256 art on 256x256
    ["arrow"] = { file = "arrow", l = 0, r = 1, t = 0, b = 1, cw = 128, ch = 128 },  -- 128x128 art on 128x128
    ["dash-eta-plate"] = { file = "dash-eta-plate", l = 0, r = 1, t = 0, b = 1, cw = 128, ch = 32 },  -- 128x32 art on 128x32
    ["dash2-housing"] = { file = "dash2-housing", l = 0, r = 1, t = 0, b = 0.625, cw = 256, ch = 512 },  -- 256x320 art on 256x512
    ["dash2-glass"] = { file = "dash2-glass", l = 0, r = 1, t = 0, b = 0.625, cw = 256, ch = 512 },  -- 256x320 art on 256x512
    ["dash2-steps-screen"] = { file = "dash2-steps-screen", l = 0, r = 1, t = 0, b = 0.625, cw = 256, ch = 512 },  -- 256x320 art on 256x512
    ["dash2-eta-screen"] = { file = "dash2-eta-screen", l = 0, r = 1, t = 0, b = 0.625, cw = 256, ch = 512 },  -- 256x320 art on 256x512
    ["dash2-compass"] = { file = "dash2-compass", l = 0, r = 1, t = 0, b = 1, cw = 256, ch = 256 },  -- 256x256 art on 256x256
    ["dash2-stop"] = { file = "dash2-stop", l = 0, r = 1, t = 0, b = 1, cw = 64, ch = 64 },  -- 64x64 art on 64x64
    ["dash2-stop-hover"] = { file = "dash2-stop-hover", l = 0, r = 1, t = 0, b = 1, cw = 64, ch = 64 },  -- 64x64 art on 64x64
    ["dash2-stop-pressed"] = { file = "dash2-stop-pressed", l = 0, r = 1, t = 0, b = 1, cw = 64, ch = 64 },  -- 64x64 art on 64x64
    ["planner-frame-wide"] = { file = "planner-frame-wide", l = 0, r = 0.634766, t = 0, b = 0.8125, cw = 1024, ch = 512 },  -- 650x416 art on 1024x512
    ["planner-panel"] = { file = "planner-panel", l = 0, r = 1, t = 0, b = 1, cw = 256, ch = 256 },  -- 256x256 art on 256x256
    ["screen-backdrop"] = { file = "screen-backdrop", l = 0, r = 1, t = 0, b = 0.800781, cw = 512, ch = 256 },  -- 512x205 art on 512x256
    ["title-plate"] = { file = "title-plate", l = 0, r = 1, t = 0, b = 1, cw = 256, ch = 64 },  -- 256x64 art on 256x64
    ["tagline-plate"] = { file = "tagline-plate", l = 0, r = 1, t = 0, b = 1, cw = 128, ch = 32 },  -- 128x32 art on 128x32
    ["input-box"] = { file = "input-box", l = 0, r = 1, t = 0, b = 1, cw = 256, ch = 32 },  -- 256x32 art on 256x32
    ["dropdown-button"] = { file = "dropdown-button", l = 0, r = 1, t = 0, b = 1, cw = 32, ch = 32 },  -- 32x32 art on 32x32
    ["button"] = { file = "button", l = 0, r = 1, t = 0, b = 1, cw = 128, ch = 32 },  -- 128x32 art on 128x32
    ["button-hover"] = { file = "button-hover", l = 0, r = 1, t = 0, b = 1, cw = 128, ch = 32 },  -- 128x32 art on 128x32
    ["button-pressed"] = { file = "button-pressed", l = 0, r = 1, t = 0, b = 1, cw = 128, ch = 32 },  -- 128x32 art on 128x32
    ["button-disabled"] = { file = "button-disabled", l = 0, r = 1, t = 0, b = 1, cw = 128, ch = 32 },  -- 128x32 art on 128x32
    ["close"] = { file = "close", l = 0, r = 1, t = 0, b = 1, cw = 32, ch = 32 },  -- 32x32 art on 32x32
    ["close-hover"] = { file = "close-hover", l = 0, r = 1, t = 0, b = 1, cw = 32, ch = 32 },  -- 32x32 art on 32x32
    ["gear"] = { file = "gear", l = 0, r = 1, t = 0, b = 1, cw = 32, ch = 32 },  -- 32x32 art on 32x32
    ["gear-hover"] = { file = "gear-hover", l = 0, r = 1, t = 0, b = 1, cw = 32, ch = 32 },  -- 32x32 art on 32x32
    ["node-ring"] = { file = "node-ring", l = 0, r = 1, t = 0, b = 1, cw = 64, ch = 64 },  -- 64x64 art on 64x64
    ["node-destination"] = { file = "node-destination", l = 0, r = 1, t = 0, b = 1, cw = 64, ch = 64 },  -- 64x64 art on 64x64
    ["icon-flight"] = { file = "icon-flight", l = 0, r = 1, t = 0, b = 1, cw = 64, ch = 64 },  -- 64x64 art on 64x64
    ["icon-boat"] = { file = "icon-boat", l = 0, r = 1, t = 0, b = 1, cw = 64, ch = 64 },  -- 64x64 art on 64x64
    ["icon-zeppelin"] = { file = "icon-zeppelin", l = 0, r = 1, t = 0, b = 1, cw = 64, ch = 64 },  -- 64x64 art on 64x64
    ["icon-tram"] = { file = "icon-tram", l = 0, r = 1, t = 0, b = 1, cw = 64, ch = 64 },  -- 64x64 art on 64x64
    ["icon-hearth"] = { file = "icon-hearth", l = 0, r = 1, t = 0, b = 1, cw = 64, ch = 64 },  -- 64x64 art on 64x64
    ["icon-walk"] = { file = "icon-walk", l = 0, r = 1, t = 0, b = 1, cw = 64, ch = 64 },  -- 64x64 art on 64x64
    ["icon-ride"] = { file = "icon-ride", l = 0, r = 1, t = 0, b = 1, cw = 64, ch = 64 },  -- 64x64 art on 64x64
    ["icon-horde"] = { file = "icon-horde", l = 0, r = 1, t = 0, b = 1, cw = 64, ch = 64 },  -- 64x64 art on 64x64
    ["icon-alliance"] = { file = "icon-alliance", l = 0, r = 1, t = 0, b = 1, cw = 64, ch = 64 },  -- 64x64 art on 64x64
    ["icon-neutral"] = { file = "icon-neutral", l = 0, r = 1, t = 0, b = 1, cw = 64, ch = 64 },  -- 64x64 art on 64x64
    ["line-solid"] = { file = "line-solid", l = 0, r = 1, t = 0, b = 1, cw = 128, ch = 16 },  -- 128x16 art on 128x16
    ["line-dashed"] = { file = "line-dashed", l = 0, r = 1, t = 0, b = 1, cw = 128, ch = 16 },  -- 128x16 art on 128x16
    ["line-dot"] = { file = "line-dot", l = 0, r = 1, t = 0, b = 1, cw = 16, ch = 16 },  -- 16x16 art on 16x16
}

ns.Data.ArtGeometry = {
    ["arrow"] = {
        ["cx"] = 0.503906,
        ["cy"] = 0.294531,
        ["share"] = 0.450195
    },
    ["canvas"] = {
        ["h"] = 1280,
        ["w"] = 1024
    },
    ["compassCrop"] = {
        ["share"] = 0.546875
    },
    ["compassRing"] = {
        ["r"] = 0.255859
    },
    ["destination"] = {
        ["bottom"] = 0.467969,
        ["left"] = 0.351562,
        ["right"] = 0.65625,
        ["top"] = 0.444531
    },
    ["distance"] = {
        ["bottom"] = 0.520312,
        ["left"] = 0.390625,
        ["right"] = 0.617188,
        ["top"] = 0.5
    },
    ["etaText"] = {
        ["bottom"] = 0.928125,
        ["left"] = 0.414062,
        ["right"] = 0.598633,
        ["top"] = 0.894531
    },
    ["glass"] = {
        ["cx"] = 0.503906,
        ["cy"] = 0.366406,
        ["r"] = 0.283203
    },
    ["planner"] = {
        ["strip"] = {
            ["labelGap"] = 0.012,
            ["lineThickness"] = 0.02,
            ["nodeDiameter"] = 0.06
        },
        ["wide"] = {
            ["canvas"] = {
                ["h"] = 1024,
                ["w"] = 1600
            },
            ["closeButton"] = {
                ["cx"] = 0.939375,
                ["cy"] = 0.217773,
                ["r"] = 0.02375
            },
            ["dropdownButton"] = {
                ["cx"] = 0.85875,
                ["cy"] = 0.322266,
                ["r"] = 0.0225
            },
            ["gearButton"] = {
                ["cx"] = 0.926875,
                ["cy"] = 0.859375,
                ["r"] = 0.02375
            },
            ["goButton"] = {
                ["bottom"] = 0.845703,
                ["left"] = 0.35,
                ["right"] = 0.65,
                ["top"] = 0.767578
            },
            ["hintLine"] = {
                ["bottom"] = 0.742188,
                ["left"] = 0.11875,
                ["right"] = 0.875,
                ["top"] = 0.705078
            },
            ["interior"] = {
                ["bottom"] = 0.857422,
                ["left"] = 0.08,
                ["right"] = 0.919375,
                ["top"] = 0.251953
            },
            ["knownLine"] = {
                ["bottom"] = 0.576172,
                ["left"] = 0.11875,
                ["right"] = 0.875,
                ["top"] = 0.535156
            },
            ["notesLine"] = {
                ["bottom"] = 0.515625,
                ["left"] = 0.11875,
                ["right"] = 0.875,
                ["top"] = 0.472656
            },
            ["resultsList"] = {
                ["bottom"] = 0.634766,
                ["left"] = 0.20625,
                ["right"] = 0.88125,
                ["top"] = 0.371094
            },
            ["screen"] = {
                ["bottom"] = 0.759766,
                ["left"] = 0.09375,
                ["right"] = 0.9,
                ["top"] = 0.376953
            },
            ["stripTrack"] = {
                ["bottom"] = 0.625,
                ["left"] = 0.14375,
                ["right"] = 0.85,
                ["top"] = 0.46875
            },
            ["taglinePlate"] = {
                ["bottom"] = 0.966797,
                ["left"] = 0.7,
                ["right"] = 0.9,
                ["top"] = 0.888672
            },
            ["titlePlate"] = {
                ["bottom"] = 0.253906,
                ["left"] = 0.3,
                ["right"] = 0.7,
                ["top"] = 0.0976562
            },
            ["toBox"] = {
                ["bottom"] = 0.365234,
                ["left"] = 0.20625,
                ["right"] = 0.83,
                ["top"] = 0.279297
            },
            ["totalLine"] = {
                ["bottom"] = 0.6875,
                ["left"] = 0.11875,
                ["right"] = 0.875,
                ["top"] = 0.650391
            }
        }
    },
    ["stepsText"] = {
        ["bottom"] = 0.845313,
        ["left"] = 0.279297,
        ["right"] = 0.731445,
        ["top"] = 0.720313
    },
    ["stop"] = {
        ["cx"] = 0.836914,
        ["cy"] = 0.170313,
        ["r"] = 0.0478516
    }
}
