-- Generated by tools/make_art.py. Do not edit.
-- Each part was scaled to the size it draws at, then padded up to a
-- power-of-two canvas. l, r, t, b crop that padding away: pass them straight
-- to texture:SetTexCoord(l, r, t, b).
local _, ns = ...
ns.Data = ns.Data or {}

ns.Data.Art = {
    ["dash-body"] = { file = "dash-body", l = 0, r = 1, t = 0, b = 1 },  -- 256x256 art on 256x256
    ["dash-screen"] = { file = "dash-screen", l = 0, r = 1, t = 0, b = 1 },  -- 256x256 art on 256x256
    ["dash-compass"] = { file = "dash-compass", l = 0, r = 1, t = 0, b = 1 },  -- 256x256 art on 256x256
    ["arrow"] = { file = "arrow", l = 0, r = 1, t = 0, b = 1 },  -- 128x128 art on 128x128
    ["dash-eta-plate"] = { file = "dash-eta-plate", l = 0, r = 1, t = 0, b = 1 },  -- 128x32 art on 128x32
}
