-- Generated by tools/make_art.py. Do not edit.
-- Each part was scaled to the size it draws at, then padded up to a
-- power-of-two canvas. l, r, t, b crop that padding away: pass them straight
-- to texture:SetTexCoord(l, r, t, b).
local _, ns = ...
ns.Data = ns.Data or {}

ns.Data.Art = {
    ["dash-body"] = { file = "dash-body", l = 0, r = 1, t = 0, b = 1 },  -- 256x256 art on 256x256
    ["dash-screen"] = { file = "dash-screen", l = 0, r = 1, t = 0, b = 1 },  -- 256x256 art on 256x256
    ["dash-compass"] = { file = "dash-compass", l = 0, r = 1, t = 0, b = 1 },  -- 256x256 art on 256x256
    ["arrow"] = { file = "arrow", l = 0, r = 1, t = 0, b = 1 },  -- 128x128 art on 128x128
    ["dash-eta-plate"] = { file = "dash-eta-plate", l = 0, r = 1, t = 0, b = 1 },  -- 128x32 art on 128x32
    ["dash2-housing"] = { file = "dash2-housing", l = 0, r = 1, t = 0, b = 0.625 },  -- 256x320 art on 256x512
    ["dash2-glass"] = { file = "dash2-glass", l = 0, r = 1, t = 0, b = 0.625 },  -- 256x320 art on 256x512
    ["dash2-steps-screen"] = { file = "dash2-steps-screen", l = 0, r = 1, t = 0, b = 0.625 },  -- 256x320 art on 256x512
    ["dash2-eta-screen"] = { file = "dash2-eta-screen", l = 0, r = 1, t = 0, b = 0.625 },  -- 256x320 art on 256x512
    ["dash2-compass"] = { file = "dash2-compass", l = 0, r = 1, t = 0, b = 1 },  -- 256x256 art on 256x256
    ["dash2-stop"] = { file = "dash2-stop", l = 0, r = 1, t = 0, b = 1 },  -- 64x64 art on 64x64
    ["dash2-stop-hover"] = { file = "dash2-stop-hover", l = 0, r = 1, t = 0, b = 1 },  -- 64x64 art on 64x64
    ["dash2-stop-pressed"] = { file = "dash2-stop-pressed", l = 0, r = 1, t = 0, b = 1 },  -- 64x64 art on 64x64
    ["planner-frame-wide"] = { file = "planner-frame-wide", l = 0, r = 0.634766, t = 0, b = 0.8125 },  -- 650x416 art on 1024x512
    ["planner-frame-tall"] = { file = "planner-frame-tall", l = 0, r = 0.75, t = 0, b = 0.585938 },  -- 384x600 art on 512x1024
    ["planner-panel"] = { file = "planner-panel", l = 0, r = 1, t = 0, b = 1 },  -- 256x256 art on 256x256
    ["screen-backdrop"] = { file = "screen-backdrop", l = 0, r = 1, t = 0, b = 0.800781 },  -- 512x205 art on 512x256
    ["title-plate"] = { file = "title-plate", l = 0, r = 1, t = 0, b = 1 },  -- 256x64 art on 256x64
    ["tagline-plate"] = { file = "tagline-plate", l = 0, r = 1, t = 0, b = 1 },  -- 128x32 art on 128x32
    ["input-box"] = { file = "input-box", l = 0, r = 1, t = 0, b = 1 },  -- 256x32 art on 256x32
    ["dropdown-button"] = { file = "dropdown-button", l = 0, r = 1, t = 0, b = 1 },  -- 32x32 art on 32x32
    ["button"] = { file = "button", l = 0, r = 1, t = 0, b = 1 },  -- 128x32 art on 128x32
    ["button-hover"] = { file = "button-hover", l = 0, r = 1, t = 0, b = 1 },  -- 128x32 art on 128x32
    ["button-pressed"] = { file = "button-pressed", l = 0, r = 1, t = 0, b = 1 },  -- 128x32 art on 128x32
    ["button-disabled"] = { file = "button-disabled", l = 0, r = 1, t = 0, b = 1 },  -- 128x32 art on 128x32
    ["close"] = { file = "close", l = 0, r = 1, t = 0, b = 1 },  -- 32x32 art on 32x32
    ["close-hover"] = { file = "close-hover", l = 0, r = 1, t = 0, b = 1 },  -- 32x32 art on 32x32
    ["gear"] = { file = "gear", l = 0, r = 1, t = 0, b = 1 },  -- 32x32 art on 32x32
    ["gear-hover"] = { file = "gear-hover", l = 0, r = 1, t = 0, b = 1 },  -- 32x32 art on 32x32
}

ns.Data.ArtGeometry = {
    ["arrow"] = {
        ["share"] = 0.450195
    },
    ["canvas"] = {
        ["h"] = 1280,
        ["w"] = 1024
    },
    ["compassCrop"] = {
        ["share"] = 0.546875
    },
    ["compassRing"] = {
        ["r"] = 0.255859
    },
    ["destination"] = {
        ["bottom"] = 0.4875,
        ["left"] = 0.351562,
        ["right"] = 0.65625,
        ["top"] = 0.464062
    },
    ["distance"] = {
        ["bottom"] = 0.510938,
        ["left"] = 0.390625,
        ["right"] = 0.617188,
        ["top"] = 0.490625
    },
    ["etaText"] = {
        ["bottom"] = 0.928125,
        ["left"] = 0.414062,
        ["right"] = 0.598633,
        ["top"] = 0.894531
    },
    ["glass"] = {
        ["cx"] = 0.503906,
        ["cy"] = 0.366406,
        ["r"] = 0.283203
    },
    ["stepsText"] = {
        ["bottom"] = 0.845313,
        ["left"] = 0.279297,
        ["right"] = 0.731445,
        ["top"] = 0.720313
    },
    ["stop"] = {
        ["cx"] = 0.836914,
        ["cy"] = 0.170313,
        ["r"] = 0.0478516
    }
}
