#!/usr/bin/env python3
"""Build GoblinPS/Media/*.tga and GoblinPS/Data/Art.lua from images/parts/*.png.

The PNGs are the source of truth and are authoring resolution: a route icon is
256 square and draws at about 24 pixels. Shipping them whole would make the
addon tens of megabytes of pixels nobody sees, so each part is scaled to the
size it actually draws at, then padded up to a power-of-two canvas, the
conservative choice for texture compatibility on this client.

Padding means the art no longer fills its texture, so each part carries the
coordinates that crop the padding away. Those live in the generated
GoblinPS/Data/Art.lua and are read by the UI; nothing hand-types them.

Run from anywhere: python tools/make_art.py
"""

from dataclasses import dataclass
from pathlib import Path

from PIL import Image

ROOT = Path(__file__).resolve().parents[1]
SOURCE = ROOT / "images" / "parts"
MEDIA = ROOT / "GoblinPS" / "Media"
TABLE = ROOT / "GoblinPS" / "Data" / "Art.lua"


@dataclass(frozen=True)
class Part:
    name: str
    width: int
    height: int


# The size each part is drawn at in the UI. The three 1024 px dash layers share
# one shipped canvas so that stacking them still lines up: their artwork is
# concentric on (512,512) and stays concentric only under one common scale.
# See images/parts/CLAUDE-HANDOFF.md.
PARTS = [
    Part("dash-body", 256, 256),
    Part("dash-screen", 256, 256),
    Part("dash-compass", 256, 256),
    Part("arrow", 128, 128),
    Part("dash-eta-plate", 128, 32),
]


def next_power_of_two(n):
    """The smallest power of two that is at least n."""
    if n < 1:
        raise ValueError("size must be positive, got {0}".format(n))
    p = 1
    while p < n:
        p *= 2
    return p


def tex_coords(art_w, art_h, canvas_w, canvas_h):
    """left, right, top, bottom for art sitting at the top-left of its canvas."""
    return (0.0, art_w / canvas_w, 0.0, art_h / canvas_h)


def build_one(part):
    src = SOURCE / "{0}.png".format(part.name)
    if not src.is_file():
        raise FileNotFoundError("{0} is missing; the art has not been delivered".format(src))
    art = Image.open(src).convert("RGBA").resize((part.width, part.height), Image.LANCZOS)
    cw, ch = next_power_of_two(part.width), next_power_of_two(part.height)
    canvas = Image.new("RGBA", (cw, ch), (0, 0, 0, 0))
    canvas.paste(art, (0, 0))            # top-left, as the authoring export does
    MEDIA.mkdir(parents=True, exist_ok=True)
    canvas.save(MEDIA / "{0}.tga".format(part.name))
    return tex_coords(part.width, part.height, cw, ch), (cw, ch)


HEADER = """-- Generated by tools/make_art.py. Do not edit.
-- Each part was scaled to the size it draws at, then padded up to a
-- power-of-two canvas. l, r, t, b crop that padding away: pass them straight
-- to texture:SetTexCoord(l, r, t, b).
local _, ns = ...
ns.Data = ns.Data or {}

ns.Data.Art = {
"""


def main():
    rows, total = [], 0
    for part in PARTS:
        (left, right, top, bottom), (cw, ch) = build_one(part)
        size = (MEDIA / "{0}.tga".format(part.name)).stat().st_size
        total += size
        rows.append(
            '    ["{0}"] = {{ file = "{0}", l = {1:g}, r = {2:g}, t = {3:g}, b = {4:g} }},'
            "  -- {5}x{6} art on {7}x{8}".format(
                part.name, left, right, top, bottom,
                part.width, part.height, cw, ch))
        print("{0}: {1}x{2} on {3}x{4}, {5:.0f} KB".format(
            part.name, part.width, part.height, cw, ch, size / 1024))
    TABLE.write_text(HEADER + "\n".join(rows) + "\n}\n", encoding="utf-8")
    print("wrote {0}".format(TABLE))
    print("{0} textures, {1:.2f} MB total".format(len(PARTS), total / 1024 / 1024))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
