import sys
import tempfile
import unittest
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
sys.path.insert(0, str(ROOT / "tools"))
import build_graph as bg  # noqa: E402

FIXTURES = Path(__file__).parent / "fixtures"


class LoadTables(unittest.TestCase):
    def test_loads_every_table(self):
        tables = bg.load_tables(FIXTURES)
        self.assertEqual(set(tables), set(bg.TABLES))

    def test_missing_table_raises(self):
        with self.assertRaises(FileNotFoundError):
            bg.load_tables(FIXTURES / "nope")

    def test_missing_column_raises(self):
        with tempfile.TemporaryDirectory() as tmp:
            for name in bg.TABLES:
                (Path(tmp) / f"{name}.csv").write_text((FIXTURES / f"{name}.csv").read_text(encoding="utf-8"),
                                                       encoding="utf-8")
            (Path(tmp) / "TaxiPath.csv").write_text("ID,FromTaxiNode,ToTaxiNode\n1,2,3\n", encoding="utf-8")
            with self.assertRaisesRegex(RuntimeError, "TaxiPath: missing columns \\['Cost'\\]"):
                bg.load_tables(Path(tmp))

    def test_read_lock_strips_whitespace(self):
        self.assertEqual(bg.read_lock(ROOT / "tools" / "catalog.lock"), "1.60.1.69913")


class Faction(unittest.TestCase):
    def test_flag_bits(self):
        self.assertEqual(bg.faction_of("1025"), "A")
        self.assertEqual(bg.faction_of("1026"), "H")
        self.assertEqual(bg.faction_of("1027"), "N")
        self.assertIsNone(bg.faction_of("1024"))
        self.assertIsNone(bg.faction_of("0"))


class Places(unittest.TestCase):
    def setUp(self):
        self.places = bg.build_places(bg.load_tables(FIXTURES))

    def test_keeps_zones_on_the_continents_only(self):
        self.assertEqual(sorted(self.places), [1411, 1413, 1454])

    def test_carries_world_bounds_and_azeroth_centre(self):
        barrens = self.places[1413]
        self.assertEqual((barrens["x0"], barrens["y0"], barrens["x1"], barrens["y1"]), (-4000, -5000, 2000, 0))
        self.assertEqual(barrens["c"], 1)
        # centre is world (-1000, -2500); Azeroth spans x 0..0.5 over world y 10000..-10000
        self.assertEqual((barrens["ax"], barrens["ay"]), (0.3125, 0.55))


class Nodes(unittest.TestCase):
    def setUp(self):
        tables = bg.load_tables(FIXTURES)
        self.nodes = bg.build_nodes(tables, bg.build_places(tables))

    def test_skips_non_player_offworld_stale_and_unmapped_nodes(self):
        self.assertEqual(sorted(self.nodes), [23, 25, 80])

    def test_trusts_the_zone_in_the_name_over_the_smallest_rectangle(self):
        # Crossroads sits inside both the Durotar and Barrens rectangles.
        self.assertEqual(self.nodes[25]["map"], 1413)

    def test_a_city_named_first_wins(self):
        self.assertEqual(self.nodes[23]["map"], 1454)

    def test_map_coords_follow_the_wow_axes(self):
        crossroads = self.nodes[25]
        # Barrens: map x = (y1 - wy) / (y1 - y0) = 2600 / 5000; map y = (x1 - wx) / (x1 - x0) = 2400 / 6000
        self.assertEqual((crossroads["mx"], crossroads["my"]), (0.52, 0.4))
        self.assertEqual((crossroads["x"], crossroads["y"], crossroads["c"], crossroads["f"]), (-400, -2600, 1, "H"))


class Flights(unittest.TestCase):
    def setUp(self):
        tables = bg.load_tables(FIXTURES)
        self.flights = bg.build_flights(tables, bg.build_nodes(tables, bg.build_places(tables)))

    def test_time_comes_from_path_length(self):
        self.assertIn([23, 25, 110, 100], self.flights)   # 3200 yards, points given out of order
        self.assertIn([25, 23, 110, 100], self.flights)   # three points
        self.assertIn([25, 80, 60, 20], self.flights)

    def test_falls_back_to_straight_line_without_points(self):
        self.assertIn([80, 25, 60, 41], self.flights)     # 1300 yards

    def test_drops_paths_to_missing_nodes(self):
        self.assertEqual(len(self.flights), 4)


class Emit(unittest.TestCase):
    def test_lua_value(self):
        self.assertEqual(bg.lua_value({"name": 'A "b"', "c": 1, "x": -2.5, "ok": True}),
                         '{c=1,name="A \\"b\\"",ok=true,x=-2.5}')
        self.assertEqual(bg.lua_value([1, 2, 110, 95]), "{1,2,110,95}")
        self.assertEqual(bg.lua_value(3.0), "3")

    def test_emit_writes_a_namespaced_lua_file(self):
        with tempfile.TemporaryDirectory() as tmp:
            bg.emit(Path(tmp), "9.9.9", "Flights", [[1, 2, 3, 4]])
            text = (Path(tmp) / "Flights.lua").read_text(encoding="utf-8")
        self.assertTrue(text.startswith("-- Generated by tools/build_graph.py from build 9.9.9. Do not edit.\n"))
        self.assertIn("local _, ns = ...\nns.Data = ns.Data or {}\nns.Data.Flights = {\n    {1,2,3,4},\n}\n", text)


if __name__ == "__main__":
    unittest.main()
